[package]
name = "cucchiaio"
version = "0.1.0"
authors = ["ddorn <diego.dorn@free.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neutrino = "0.3.1"